# Generated by Django 5.1a1 on 2024-05-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0021_remove_admin_situacao_alter_cadastro_cozinha"),
    ]

    operations = [
        migrations.CreateModel(
            name="EsqueciSenha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="E-e-mail")),
            ],
        ),
        migrations.AddField(
            model_name="membrofamilia",
            name="situacao_atual",
            field=models.CharField(
                choices=[("Ativo.", "Atuante "), ("Inativo", "Ausente")],
                default="Atuante",
                max_length=255,
                null=True,
                verbose_name="situacao atual",
            ),
        ),
    ]
