# Generated by Django 5.1a1 on 2024-05-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0022_esquecisenha_membrofamilia_situacao_atual"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="cod_acesso",
            field=models.CharField(
                default="", max_length=15, null=True, verbose_name="codigo de acesso"
            ),
        ),
        migrations.AddField(
            model_name="admin",
            name="situacao_atual",
            field=models.CharField(
                choices=[("Adm.", "administração "), ("Gte.", "Gerente")],
                default="Adm",
                max_length=15,
                null=True,
                verbose_name="situacao atual",
            ),
        ),
        migrations.AlterField(
            model_name="membrofamilia",
            name="situacao_atual",
            field=models.CharField(
                choices=[("Ativo.", "Atuante "), ("Inativo", "Ausente")],
                default="Atuante",
                max_length=15,
                null=True,
                verbose_name="situacao atual",
            ),
        ),
    ]
