# Generated by Django 5.1a1 on 2024-05-31 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0023_admin_cod_acesso_admin_situacao_atual_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="esquecisenha",
            options={
                "verbose_name": "Esqueci Minha Senha",
                "verbose_name_plural": "Esqueci Minhas Senhas",
            },
        ),
        migrations.RemoveField(
            model_name="esquecisenha",
            name="email",
        ),
    ]
