# Generated by Django 5.1a1 on 2024-05-31 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0024_alter_esquecisenha_options_remove_esquecisenha_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="esquecisenha",
            options={},
        ),
    ]
