# Generated by Django 5.1a1 on 2024-05-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0025_alter_esquecisenha_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="esquecisenha",
            name="email",
            field=models.EmailField(default=0, max_length=255, verbose_name="E-e-mail"),
            preserve_default=False,
        ),
    ]
