# Generated by Django 5.1a1 on 2024-06-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0026_esquecisenha_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membrofamilia",
            name="celular",
            field=models.CharField(
                blank=True,
                help_text="Digite seu Telefone aqui. como no exemplo: (21) 9xxxx-xxxx",
                max_length=15,
                verbose_name="Celular",
            ),
        ),
    ]
