# Generated by Django 5.1a1 on 2024-06-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0027_alter_membrofamilia_celular"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="email",
            field=models.EmailField(
                error_messages={
                    "blank": "Este campo não pode ficar em branco.",
                    "invalid": "O valor fornecido é inválido, verifique se tem @.",
                },
                help_text="Digite o E-mail aqui.",
                max_length=255,
                unique=True,
                verbose_name="E-e-mail",
            ),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="celular",
            field=models.CharField(
                blank=True,
                help_text="Digite seu Telefone aqui. como no exemplo: (21) 9xxxx-xxxx",
                max_length=15,
                verbose_name="Celular",
            ),
        ),
        migrations.AlterField(
            model_name="cadastrovoluntario",
            name="email",
            field=models.EmailField(
                error_messages={
                    "blank": "Este campo não pode ficar em branco.",
                    "invalid": "O valor fornecido é inválido, verifique se tem @.",
                },
                help_text="Digite o E-mail aqui.",
                max_length=255,
                unique=True,
                verbose_name="E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="esquecisenha",
            name="email",
            field=models.EmailField(max_length=255, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="login",
            name="email",
            field=models.EmailField(max_length=255, verbose_name="E-mail"),
        ),
    ]
